dataset = ["SYNTHETIC"]
imputation = ["MICE", "GAIN", "Mean"]
train_percentage = [0.25, 0.5]
test_percentage = [0.5]
holdout_set = [0, 1, 2]
val_set = [0, 1, 2, 3, 4]
repeat = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

